function letters(varargin)
    w = linspace(0, pi, 20)';
    T = [.8 1; .52 1; .52 0; .48 0; .48 1; .2 1];
    U = [.2 1; .5 - cos(w) * .3 .3 - sin(w) * .3; .8 1];
    N = [.8 1; .8 0; .2 1; .2 0];
    I = [.5 0; .5 1];
    p = [T; U; N; I];
    margin = 0.5;
    width = 7; % mm
    height = 6;
    paths = [p(:, 1) 1 - p(:, 2)] .* ([width height] - 2 * margin) + margin;
    control_loop('logname', 'letters', ...
        'paths', paths, ...
        'draw', true, ...
        'maxsegment', 0.1, ...
        'controller', 'sfb', ...
        'sparse_file', 'sfb_model.mat', ...
        'save_images', true, ...
        varargin{:});
end
