function repeated_rectangle(varargin)
    paths = [1, 1; repmat([6, 1; 6, 5; 1, 5; 1, 1], 5, 1)];
    % NO sparse saving and NO loading trained model; we want to start
    % from blank. We want to see if the second cycle is better than first.
    control_loop( ...
    'logname', 'repeated_rectangle', ...
        'paths', paths, ...
        'draw', true, ...
        'maxsegment', 0.1, ...
        'controller', 'sfb', ...
        'save_images', true, ...
        varargin{:});
    % For eps-greedy test, just change controller to 'eps-greedy'
end
